### ISSUE TITLE
Typescript error: 'onChange' in type 'BaseLocationServices' is not assignable to the same property in base type 'LocationServices'

### ISSUE THREAD

**Issue by sebastianhaeni** [ui-router/core#229]
Since version `5.0.21` I'm getting the following TypeScript error when compiling:

    node_modules/@uirouter/core/lib/vanilla/baseLocationService.d.ts:43:5 - error TS2416: Property 'onChange' in type 'BaseLocationServices' is not assignable to the same property in base type 'LocationServices'.
      Type '(cb: EventListener) => () => Function[]' is not assignable to type '(callback: Function) => Function'.
        Types of parameters 'cb' and 'callback' are incompatible.
          Type 'Function' is not assignable to type 'EventListener'.
            Type 'Function' provides no match for the signature '(evt: Event): void'.
    
    43:     onChange(cb: EventListener): () => Function[];
            ~~~~~~~~

Is there something wrong with my configuration or my imports? It worked with `5.0.20`.

Seems like the change was made in https://github.com/ui-router/core/commit/095f531977971de387c619024c284f0f4df375d6 .

**Comment by robertomatute** [comment]
I am using angular-hybrid `6.0.2`and getting the same error:
```
ERROR in node_modules/@uirouter/core/lib/vanilla/baseLocationService.d.ts(43,5): error TS2416: Property 'onChange' in type 'BaseLocationServices' is not assignable to the same property in base type 'LocationServices'.
  Type '(cb: EventListener) => () => Function[]' is not assignable to type '(callback: Function) => Function'.
    Types of parameters 'cb' and 'callback' are incompatible.
      Type 'Function' is not assignable to type 'EventListener'.
        Type 'Function' provides no match for the signature '(evt: Event): void'.
```
This module uses the same core version `5.0.21`.

**Comment by renaldas-kerpe-arria** [comment]
Same here with `"@uirouter/angular-hybrid": "^6.0.2"`

**Comment by tommck** [comment]
Ugh.. I assumed this would be fixed in 5.0.22

**Comment by tommck** [comment]
yikes, that change set was marked as "(docs)", but was NOT just docs. It changed code

**Comment by renaldas-kerpe-arria** [comment]
Ping @christopherthielen

**Comment by christopherthielen** [comment]
How do I reproduce this typescript error?

**Comment by tommck** [comment]
You rock!

**Comment by renaldas-kerpe-arria** [comment]
🎉
